# Copyright (C) 2026 AnkiCraft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

from typing import Final

from anki import lang as anki_lang

FALLBACK_LANG: Final[str] = "en"

_STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "dialog_title": "Restart",
        "restart_checkbox": "Enable shortcut to restart Anki",
        "close_checkbox": "Enable shortcut to close Anki",
        "shortcut_label": "Shortcut:",
        "restore_defaults": "Restore defaults",
        "duplicate_shortcut": "The two shortcuts cannot be the same key combination.",
        "error_title": "Quick Restart — Error",
        "executable_not_found": "Anki's program file could not be found, so it cannot restart. Anki stays open and nothing was lost.",
        "unexpected_error": "An unexpected error occurred:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Buy me a coffee",
        "kofi_tooltip": "Support development on Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Rate this add-on",
        "report_button": "Report a bug",
        "welcome_close": "Close",
        "welcome_body": "Quick Restart adds a shortcut to instantly restart or close Anki, so you don't have to reach for the mouse. You can change the shortcuts anytime from Tools → Add-ons → Config.",
        "welcome_support_note": "This add-on is free and open source (AGPLv3). If you find it useful, consider supporting its development.",
    },
    "es": {
        "dialog_title": "Restart",
        "restart_checkbox": "Activar atajo para reiniciar Anki",
        "close_checkbox": "Activar atajo para cerrar Anki",
        "shortcut_label": "Atajo:",
        "restore_defaults": "Restaurar los valores predeterminados",
        "duplicate_shortcut": "Los dos atajos no pueden ser la misma combinación de teclas.",
        "error_title": "Reinicio rápido — Error",
        "executable_not_found": "No se encontró el programa de Anki, así que no se puede reiniciar. Anki sigue abierto y no se ha perdido nada.",
        "unexpected_error": "Ocurrió un error inesperado:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Apoya el desarrollo en Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Valorar este complemento",
        "report_button": "Reportar un error",
        "welcome_close": "Cerrar",
        "welcome_body": "Quick Restart añade un atajo de teclado para reiniciar o cerrar Anki al instante, sin tocar el ratón. Puedes cambiar los atajos cuando quieras desde Herramientas → Complementos → Config.",
        "welcome_support_note": "Este complemento es gratuito y de código abierto (AGPLv3). Si te resulta útil, considera apoyar su desarrollo.",
    },
    "af": {
        "dialog_title": "Restart",
        "restart_checkbox": "Aktiveer kortpad om Anki te herbegin",
        "close_checkbox": "Aktiveer kortpad om Anki toe te maak",
        "shortcut_label": "Kortpad:",
        "restore_defaults": "Herstel verstekwaardes",
        "duplicate_shortcut": "Die twee kortpaaie mag nie dieselfde sleutelkombinasie wees nie.",
        "error_title": "Vinnige herbegin — Fout",
        "executable_not_found": "Anki se programlêer kon nie gevind word nie, dus kan dit nie herbegin nie. Anki bly oop en niks is verloor nie.",
        "unexpected_error": "'n Onverwagte fout het voorgekom:\n\n{error}",
    },
    "ar": {
        "dialog_title": "Restart",
        "restart_checkbox": "تفعيل اختصار إعادة تشغيل Anki",
        "close_checkbox": "تفعيل اختصار إغلاق Anki",
        "shortcut_label": "الاختصار:",
        "restore_defaults": "استعادة القيم الافتراضية",
        "duplicate_shortcut": "لا يمكن أن يكون الاختصاران نفس تركيبة المفاتيح.",
        "error_title": "إعادة تشغيل سريعة — خطأ",
        "executable_not_found": "تعذّر العثور على ملف برنامج Anki، لذا لا يمكن إعادة التشغيل. يبقى Anki مفتوحًا ولم يُفقد أي شيء.",
        "unexpected_error": "حدث خطأ غير متوقع:\n\n{error}",
    },
    "be": {
        "dialog_title": "Restart",
        "restart_checkbox": "Уключыць спалучэнне для перазапуску Anki",
        "close_checkbox": "Уключыць спалучэнне для закрыцця Anki",
        "shortcut_label": "Спалучэнне:",
        "restore_defaults": "Аднавіць прадвызначаныя значэнні",
        "duplicate_shortcut": "Два спалучэнні клавіш не могуць супадаць.",
        "error_title": "Хуткі перазапуск — Памылка",
        "executable_not_found": "Не ўдалося знайсці праграмны файл Anki, таму перазапуск немагчымы. Anki застаецца адкрытым, нічога не страчана.",
        "unexpected_error": "Адбылася нечаканая памылка:\n\n{error}",
    },
    "bg": {
        "dialog_title": "Restart",
        "restart_checkbox": "Включи клавишна комбинация за рестартиране на Anki",
        "close_checkbox": "Включи клавишна комбинация за затваряне на Anki",
        "shortcut_label": "Комбинация:",
        "restore_defaults": "Възстанови стойностите по подразбиране",
        "duplicate_shortcut": "Двете комбинации не могат да бъдат едни и същи.",
        "error_title": "Бързо рестартиране — Грешка",
        "executable_not_found": "Програмният файл на Anki не беше намерен, затова рестартирането е невъзможно. Anki остава отворен и нищо не е загубено.",
        "unexpected_error": "Възникна неочаквана грешка:\n\n{error}",
    },
    "ca": {
        "dialog_title": "Restart",
        "restart_checkbox": "Activa la drecera per reiniciar l'Anki",
        "close_checkbox": "Activa la drecera per tancar l'Anki",
        "shortcut_label": "Drecera:",
        "restore_defaults": "Restaura els valors predeterminats",
        "duplicate_shortcut": "Les dues dreceres no poden ser la mateixa combinació de tecles.",
        "error_title": "Reinici ràpid — Error",
        "executable_not_found": "No s'ha trobat el programa de l'Anki, així que no es pot reiniciar. L'Anki continua obert i no s'ha perdut res.",
        "unexpected_error": "S'ha produït un error inesperat:\n\n{error}",
    },
    "cs": {
        "dialog_title": "Restart",
        "restart_checkbox": "Zapnout zkratku pro restart Anki",
        "close_checkbox": "Zapnout zkratku pro zavření Anki",
        "shortcut_label": "Zkratka:",
        "restore_defaults": "Obnovit výchozí hodnoty",
        "duplicate_shortcut": "Obě zkratky nemohou být stejná kombinace kláves.",
        "error_title": "Rychlý restart — Chyba",
        "executable_not_found": "Program Anki se nepodařilo najít, takže jej nelze restartovat. Anki zůstává otevřené a nic se neztratilo.",
        "unexpected_error": "Došlo k neočekávané chybě:\n\n{error}",
    },
    "da": {
        "dialog_title": "Restart",
        "restart_checkbox": "Aktivér genvej til at genstarte Anki",
        "close_checkbox": "Aktivér genvej til at lukke Anki",
        "shortcut_label": "Genvej:",
        "restore_defaults": "Gendan standardværdier",
        "duplicate_shortcut": "De to genveje må ikke være den samme tastekombination.",
        "error_title": "Hurtig genstart — Fejl",
        "executable_not_found": "Ankis programfil blev ikke fundet, så den kan ikke genstartes. Anki forbliver åben, og intet er gået tabt.",
        "unexpected_error": "Der opstod en uventet fejl:\n\n{error}",
    },
    "de": {
        "dialog_title": "Restart",
        "restart_checkbox": "Tastenkürzel zum Neustarten von Anki aktivieren",
        "close_checkbox": "Tastenkürzel zum Schließen von Anki aktivieren",
        "shortcut_label": "Tastenkürzel:",
        "restore_defaults": "Standardwerte wiederherstellen",
        "duplicate_shortcut": "Die beiden Tastenkürzel dürfen nicht dieselbe Tastenkombination sein.",
        "error_title": "Schnellneustart — Fehler",
        "executable_not_found": "Die Programmdatei von Anki wurde nicht gefunden, daher ist kein Neustart möglich. Anki bleibt geöffnet und es ging nichts verloren.",
        "unexpected_error": "Ein unerwarteter Fehler ist aufgetreten:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Unterstütze die Entwicklung auf Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Erweiterung bewerten",
        "report_button": "Fehler melden",
        "welcome_close": "Schließen",
        "welcome_body": "Quick Restart fügt ein Tastenkürzel hinzu, um Anki sofort neu zu starten oder zu schließen, ganz ohne Maus. Die Tastenkürzel lassen sich jederzeit unter Extras → Erweiterungen → Konfiguration ändern.",
        "welcome_support_note": "Diese Erweiterung ist kostenlos und quelloffen (AGPLv3). Wenn sie dir nützlich ist, unterstütze gerne ihre Entwicklung.",
    },
    "el": {
        "dialog_title": "Restart",
        "restart_checkbox": "Ενεργοποίηση συντόμευσης για επανεκκίνηση του Anki",
        "close_checkbox": "Ενεργοποίηση συντόμευσης για κλείσιμο του Anki",
        "shortcut_label": "Συντόμευση:",
        "restore_defaults": "Επαναφορά προεπιλογών",
        "duplicate_shortcut": "Οι δύο συντομεύσεις δεν μπορούν να είναι ο ίδιος συνδυασμός πλήκτρων.",
        "error_title": "Γρήγορη επανεκκίνηση — Σφάλμα",
        "executable_not_found": "Δεν βρέθηκε το εκτελέσιμο αρχείο του Anki, οπότε δεν μπορεί να γίνει επανεκκίνηση. Το Anki παραμένει ανοιχτό και δεν χάθηκε τίποτα.",
        "unexpected_error": "Παρουσιάστηκε απροσδόκητο σφάλμα:\n\n{error}",
    },
    "eo": {
        "dialog_title": "Restart",
        "restart_checkbox": "Ŝalti klavkombinon por restartigi Anki",
        "close_checkbox": "Ŝalti klavkombinon por fermi Anki",
        "shortcut_label": "Klavkombino:",
        "restore_defaults": "Restarigi defaŭltajn valorojn",
        "duplicate_shortcut": "La du klavkombinoj ne povas esti la sama.",
        "error_title": "Rapida restartigo — Eraro",
        "executable_not_found": "La programdosiero de Anki ne troviĝis, do ĝi ne povas restartiĝi. Anki restas malfermita kaj nenio perdiĝis.",
        "unexpected_error": "Okazis neatendita eraro:\n\n{error}",
    },
    "et": {
        "dialog_title": "Restart",
        "restart_checkbox": "Luba kiirklahv Anki taaskäivitamiseks",
        "close_checkbox": "Luba kiirklahv Anki sulgemiseks",
        "shortcut_label": "Kiirklahv:",
        "restore_defaults": "Taasta vaikeväärtused",
        "duplicate_shortcut": "Kaks kiirklahvi ei tohi olla sama klahvikombinatsioon.",
        "error_title": "Kiire taaskäivitus — Viga",
        "executable_not_found": "Anki programmifaili ei leitud, seega ei saa taaskäivitada. Anki jääb avatuks ja midagi ei läinud kaotsi.",
        "unexpected_error": "Ilmnes ootamatu viga:\n\n{error}",
    },
    "eu": {
        "dialog_title": "Restart",
        "restart_checkbox": "Gaitu Anki berrabiarazteko lasterbidea",
        "close_checkbox": "Gaitu Anki ixteko lasterbidea",
        "shortcut_label": "Lasterbidea:",
        "restore_defaults": "Leheneratu balio lehenetsiak",
        "duplicate_shortcut": "Bi lasterbideak ezin dira tekla-konbinazio bera izan.",
        "error_title": "Berrabiarazte azkarra — Errorea",
        "executable_not_found": "Ez da Ankiren programa-fitxategia aurkitu, beraz ezin da berrabiarazi. Anki irekita jarraitzen du eta ez da ezer galdu.",
        "unexpected_error": "Ustekabeko errore bat gertatu da:\n\n{error}",
    },
    "fa": {
        "dialog_title": "Restart",
        "restart_checkbox": "فعال‌سازی میان‌بر راه‌اندازی مجدد Anki",
        "close_checkbox": "فعال‌سازی میان‌بر بستن Anki",
        "shortcut_label": "میان‌بر:",
        "restore_defaults": "بازگرداندن مقادیر پیش‌فرض",
        "duplicate_shortcut": "دو میان‌بر نمی‌توانند ترکیب کلید یکسانی داشته باشند.",
        "error_title": "راه‌اندازی مجدد سریع — خطا",
        "executable_not_found": "فایل برنامهٔ Anki پیدا نشد، بنابراین راه‌اندازی مجدد ممکن نیست. Anki باز می‌ماند و چیزی از دست نرفته است.",
        "unexpected_error": "خطای غیرمنتظره‌ای رخ داد:\n\n{error}",
    },
    "fi": {
        "dialog_title": "Restart",
        "restart_checkbox": "Ota käyttöön pikanäppäin Ankin uudelleenkäynnistykseen",
        "close_checkbox": "Ota käyttöön pikanäppäin Ankin sulkemiseen",
        "shortcut_label": "Pikanäppäin:",
        "restore_defaults": "Palauta oletusarvot",
        "duplicate_shortcut": "Pikanäppäimet eivät voi olla sama näppäinyhdistelmä.",
        "error_title": "Nopea uudelleenkäynnistys — Virhe",
        "executable_not_found": "Ankin ohjelmatiedostoa ei löytynyt, joten uudelleenkäynnistys ei onnistu. Anki pysyy auki eikä mitään menetetty.",
        "unexpected_error": "Tapahtui odottamaton virhe:\n\n{error}",
    },
    "fr": {
        "dialog_title": "Restart",
        "restart_checkbox": "Activer le raccourci pour redémarrer Anki",
        "close_checkbox": "Activer le raccourci pour fermer Anki",
        "shortcut_label": "Raccourci :",
        "restore_defaults": "Restaurer les valeurs par défaut",
        "duplicate_shortcut": "Les deux raccourcis ne peuvent pas être la même combinaison de touches.",
        "error_title": "Redémarrage rapide — Erreur",
        "executable_not_found": "Le fichier programme d'Anki est introuvable, le redémarrage est donc impossible. Anki reste ouvert et rien n'a été perdu.",
        "unexpected_error": "Une erreur inattendue s'est produite :\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Soutenez le développement sur Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Évaluer ce module",
        "report_button": "Signaler un bug",
        "welcome_close": "Fermer",
        "welcome_body": "Quick Restart ajoute un raccourci pour redémarrer ou fermer Anki instantanément, sans toucher la souris. Vous pouvez modifier les raccourcis à tout moment dans Outils → Modules complémentaires → Config.",
        "welcome_support_note": "Ce module est gratuit et open source (AGPLv3). S'il vous est utile, pensez à soutenir son développement.",
    },
    "ga": {
        "dialog_title": "Restart",
        "restart_checkbox": "Cumasaigh aicearra chun Anki a atosú",
        "close_checkbox": "Cumasaigh aicearra chun Anki a dhúnadh",
        "shortcut_label": "Aicearra:",
        "restore_defaults": "Athchóirigh na réamhshocruithe",
        "duplicate_shortcut": "Ní féidir leis an dá aicearra a bheith mar an gcéanna.",
        "error_title": "Atosú tapa — Earráid",
        "executable_not_found": "Níorbh fhéidir comhad cláir Anki a aimsiú, mar sin ní féidir é a atosú. Fanann Anki oscailte agus níor cailleadh aon rud.",
        "unexpected_error": "Tharla earráid gan choinne:\n\n{error}",
    },
    "gl": {
        "dialog_title": "Restart",
        "restart_checkbox": "Activar atallo para reiniciar Anki",
        "close_checkbox": "Activar atallo para pechar Anki",
        "shortcut_label": "Atallo:",
        "restore_defaults": "Restaurar os valores predeterminados",
        "duplicate_shortcut": "Os dous atallos non poden ser a mesma combinación de teclas.",
        "error_title": "Reinicio rápido — Erro",
        "executable_not_found": "Non se atopou o programa de Anki, así que non se pode reiniciar. Anki segue aberto e non se perdeu nada.",
        "unexpected_error": "Produciuse un erro inesperado:\n\n{error}",
    },
    "he": {
        "dialog_title": "Restart",
        "restart_checkbox": "הפעלת קיצור דרך להפעלה מחדש של Anki",
        "close_checkbox": "הפעלת קיצור דרך לסגירת Anki",
        "shortcut_label": "קיצור דרך:",
        "restore_defaults": "שחזור ברירות המחדל",
        "duplicate_shortcut": "שני קיצורי הדרך אינם יכולים להיות אותו צירוף מקשים.",
        "error_title": "הפעלה מחדש מהירה — שגיאה",
        "executable_not_found": "קובץ התוכנה של Anki לא נמצא, ולכן אי אפשר להפעיל מחדש. Anki נשאר פתוח ודבר לא אבד.",
        "unexpected_error": "אירעה שגיאה בלתי צפויה:\n\n{error}",
    },
    "hi": {
        "dialog_title": "Restart",
        "restart_checkbox": "Anki को पुनरारंभ करने का शॉर्टकट सक्षम करें",
        "close_checkbox": "Anki को बंद करने का शॉर्टकट सक्षम करें",
        "shortcut_label": "शॉर्टकट:",
        "restore_defaults": "डिफ़ॉल्ट मान पुनर्स्थापित करें",
        "duplicate_shortcut": "दोनों शॉर्टकट एक ही कुंजी संयोजन नहीं हो सकते।",
        "error_title": "त्वरित पुनरारंभ — त्रुटि",
        "executable_not_found": "Anki की प्रोग्राम फ़ाइल नहीं मिली, इसलिए पुनरारंभ नहीं हो सकता। Anki खुला रहेगा और कुछ भी नहीं खोया।",
        "unexpected_error": "एक अप्रत्याशित त्रुटि हुई:\n\n{error}",
    },
    "hr": {
        "dialog_title": "Restart",
        "restart_checkbox": "Omogući prečac za ponovno pokretanje Ankija",
        "close_checkbox": "Omogući prečac za zatvaranje Ankija",
        "shortcut_label": "Prečac:",
        "restore_defaults": "Vrati zadane vrijednosti",
        "duplicate_shortcut": "Dva prečaca ne mogu biti ista kombinacija tipki.",
        "error_title": "Brzo ponovno pokretanje — Pogreška",
        "executable_not_found": "Programska datoteka Ankija nije pronađena pa se ne može ponovno pokrenuti. Anki ostaje otvoren i ništa nije izgubljeno.",
        "unexpected_error": "Došlo je do neočekivane pogreške:\n\n{error}",
    },
    "hu": {
        "dialog_title": "Restart",
        "restart_checkbox": "Gyorsbillentyű engedélyezése az Anki újraindításához",
        "close_checkbox": "Gyorsbillentyű engedélyezése az Anki bezárásához",
        "shortcut_label": "Gyorsbillentyű:",
        "restore_defaults": "Alapértelmezett értékek visszaállítása",
        "duplicate_shortcut": "A két gyorsbillentyű nem lehet ugyanaz a billentyűkombináció.",
        "error_title": "Gyors újraindítás — Hiba",
        "executable_not_found": "Az Anki programfájlja nem található, ezért nem indítható újra. Az Anki nyitva marad, és semmi sem veszett el.",
        "unexpected_error": "Váratlan hiba történt:\n\n{error}",
    },
    "hy": {
        "dialog_title": "Restart",
        "restart_checkbox": "Միացնել Anki-ն վերագործարկելու կապակցումը",
        "close_checkbox": "Միացնել Anki-ն փակելու կապակցումը",
        "shortcut_label": "Կապակցում՝",
        "restore_defaults": "Վերականգնել լռելյայն արժեքները",
        "duplicate_shortcut": "Երկու կապակցումները չեն կարող լինել նույն ստեղների համակցությունը։",
        "error_title": "Արագ վերագործարկում — Սխալ",
        "executable_not_found": "Anki-ի ծրագրային ֆայլը չգտնվեց, ուստի վերագործարկումն անհնար է։ Anki-ն մնում է բաց, և ոչինչ չի կորել։",
        "unexpected_error": "Տեղի ունեցավ անսպասելի սխալ՝\n\n{error}",
    },
    "id": {
        "dialog_title": "Restart",
        "restart_checkbox": "Aktifkan pintasan untuk memulai ulang Anki",
        "close_checkbox": "Aktifkan pintasan untuk menutup Anki",
        "shortcut_label": "Pintasan:",
        "restore_defaults": "Pulihkan nilai bawaan",
        "duplicate_shortcut": "Kedua pintasan tidak boleh berupa kombinasi tombol yang sama.",
        "error_title": "Mulai Ulang Cepat — Kesalahan",
        "executable_not_found": "Berkas program Anki tidak ditemukan, sehingga tidak dapat dimulai ulang. Anki tetap terbuka dan tidak ada yang hilang.",
        "unexpected_error": "Terjadi kesalahan yang tidak terduga:\n\n{error}",
    },
    "it": {
        "dialog_title": "Restart",
        "restart_checkbox": "Attiva la scorciatoia per riavviare Anki",
        "close_checkbox": "Attiva la scorciatoia per chiudere Anki",
        "shortcut_label": "Scorciatoia:",
        "restore_defaults": "Ripristina i valori predefiniti",
        "duplicate_shortcut": "Le due scorciatoie non possono essere la stessa combinazione di tasti.",
        "error_title": "Riavvio rapido — Errore",
        "executable_not_found": "Il file del programma Anki non è stato trovato, quindi non è possibile riavviarlo. Anki resta aperto e non è andato perso nulla.",
        "unexpected_error": "Si è verificato un errore imprevisto:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Sostieni lo sviluppo su Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Valuta questo componente",
        "report_button": "Segnala un bug",
        "welcome_close": "Chiudi",
        "welcome_body": "Quick Restart aggiunge una scorciatoia per riavviare o chiudere Anki all'istante, senza usare il mouse. Puoi modificare le scorciatoie in qualsiasi momento da Strumenti → Componenti aggiuntivi → Configura.",
        "welcome_support_note": "Questo componente aggiuntivo è gratuito e open source (AGPLv3). Se lo trovi utile, valuta di sostenerne lo sviluppo.",
    },
    "ja": {
        "dialog_title": "Restart",
        "restart_checkbox": "Anki を再起動するショートカットを有効にする",
        "close_checkbox": "Anki を終了するショートカットを有効にする",
        "shortcut_label": "ショートカット:",
        "restore_defaults": "既定値に戻す",
        "duplicate_shortcut": "2 つのショートカットに同じキーの組み合わせは使えません。",
        "error_title": "クイック再起動 — エラー",
        "executable_not_found": "Anki の実行ファイルが見つからないため、再起動できません。Anki は開いたままで、データは失われていません。",
        "unexpected_error": "予期しないエラーが発生しました:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Ko-fi で開発を支援する",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 このアドオンを評価",
        "report_button": "バグを報告",
        "welcome_close": "閉じる",
        "welcome_body": "Quick Restart は、マウスを使わずに Anki を瞬時に再起動または終了できるショートカットを追加します。ショートカットはツール → アドオン → 設定 からいつでも変更できます。",
        "welcome_support_note": "このアドオンは無料でオープンソース（AGPLv3）です。役に立ったら、開発への支援をご検討ください。",
    },
    "jbo": {
        "dialog_title": "Restart",
        "restart_checkbox": "kakne le batkyseltcu poi za'ureci'a la .anki.",
        "close_checkbox": "kakne le batkyseltcu poi sisti la .anki.",
        "shortcut_label": "batkyseltcu:",
        "restore_defaults": "xruti fi le krasi",
        "duplicate_shortcut": "le re batkyseltcu na ka'e mintu",
        "error_title": "sutra za'ureci'a — nabmi",
        "executable_not_found": "na facki le samtci be la .anki. .i seri'a na ka'e za'ureci'a .i la .anki. ca'o kalri gi'e na cirko",
        "unexpected_error": "da nabmi cu fasnu:\n\n{error}",
    },
    "ko": {
        "dialog_title": "Restart",
        "restart_checkbox": "Anki 재시작 단축키 사용",
        "close_checkbox": "Anki 닫기 단축키 사용",
        "shortcut_label": "단축키:",
        "restore_defaults": "기본값 복원",
        "duplicate_shortcut": "두 단축키는 같은 키 조합일 수 없습니다.",
        "error_title": "빠른 재시작 — 오류",
        "executable_not_found": "Anki 실행 파일을 찾을 수 없어 재시작할 수 없습니다. Anki는 계속 열려 있으며 잃어버린 데이터는 없습니다.",
        "unexpected_error": "예기치 않은 오류가 발생했습니다:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Ko-fi에서 개발 후원하기",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 부가기능 평가하기",
        "report_button": "버그 신고",
        "welcome_close": "닫기",
        "welcome_body": "Quick Restart는 마우스를 사용하지 않고도 Anki를 즉시 재시작하거나 종료할 수 있는 단축키를 추가합니다. 단축키는 언제든지 도구 → 부가기능 → 설정에서 변경할 수 있습니다.",
        "welcome_support_note": "이 부가기능은 무료이며 오픈소스(AGPLv3)입니다. 유용하다고 느끼신다면 개발을 후원해 주세요.",
    },
    "la": {
        "dialog_title": "Restart",
        "restart_checkbox": "Compendiariam ad Anki recurrendum permittere",
        "close_checkbox": "Compendiariam ad Anki claudendum permittere",
        "shortcut_label": "Compendiaria:",
        "restore_defaults": "Valores primos restituere",
        "duplicate_shortcut": "Duae compendiariae eaedem esse non possunt.",
        "error_title": "Recursus celer — Error",
        "executable_not_found": "Programma Anki inveniri non potuit, ergo recurrere non potest. Anki apertum manet et nihil amissum est.",
        "unexpected_error": "Error inopinatus accidit:\n\n{error}",
    },
    "lt": {
        "dialog_title": "Restart",
        "restart_checkbox": "Įjungti spartųjį klavišą Anki paleidimui iš naujo",
        "close_checkbox": "Įjungti spartųjį klavišą Anki uždarymui",
        "shortcut_label": "Spartusis klavišas:",
        "restore_defaults": "Atkurti numatytąsias reikšmes",
        "duplicate_shortcut": "Abu spartieji klavišai negali būti ta pati klavišų kombinacija.",
        "error_title": "Greitas paleidimas iš naujo — Klaida",
        "executable_not_found": "Anki programos failas nerastas, todėl paleisti iš naujo negalima. Anki lieka atidarytas ir niekas neprarasta.",
        "unexpected_error": "Įvyko netikėta klaida:\n\n{error}",
    },
    "lv": {
        "dialog_title": "Restart",
        "restart_checkbox": "Ieslēgt īsinājumtaustiņu Anki pārstartēšanai",
        "close_checkbox": "Ieslēgt īsinājumtaustiņu Anki aizvēršanai",
        "shortcut_label": "Īsinājumtaustiņš:",
        "restore_defaults": "Atjaunot noklusējuma vērtības",
        "duplicate_shortcut": "Abi īsinājumtaustiņi nevar būt viena un tā pati taustiņu kombinācija.",
        "error_title": "Ātrā pārstartēšana — Kļūda",
        "executable_not_found": "Anki programmas fails netika atrasts, tāpēc to nevar pārstartēt. Anki paliek atvērts, un nekas nav zaudēts.",
        "unexpected_error": "Radās negaidīta kļūda:\n\n{error}",
    },
    "mn": {
        "dialog_title": "Restart",
        "restart_checkbox": "Anki-г дахин эхлүүлэх товчлолыг идэвхжүүлэх",
        "close_checkbox": "Anki-г хаах товчлолыг идэвхжүүлэх",
        "shortcut_label": "Товчлол:",
        "restore_defaults": "Анхны утгыг сэргээх",
        "duplicate_shortcut": "Хоёр товчлол ижил байж болохгүй.",
        "error_title": "Хурдан дахин эхлүүлэх — Алдаа",
        "executable_not_found": "Anki программын файл олдсонгүй тул дахин эхлүүлэх боломжгүй. Anki нээлттэй хэвээр байгаа бөгөөд юу ч алдагдаагүй.",
        "unexpected_error": "Гэнэтийн алдаа гарлаа:\n\n{error}",
    },
    "ms": {
        "dialog_title": "Restart",
        "restart_checkbox": "Aktifkan pintasan untuk memulakan semula Anki",
        "close_checkbox": "Aktifkan pintasan untuk menutup Anki",
        "shortcut_label": "Pintasan:",
        "restore_defaults": "Pulihkan nilai lalai",
        "duplicate_shortcut": "Kedua-dua pintasan tidak boleh menggunakan gabungan kekunci yang sama.",
        "error_title": "Mula Semula Pantas — Ralat",
        "executable_not_found": "Fail program Anki tidak ditemui, jadi ia tidak boleh dimulakan semula. Anki kekal terbuka dan tiada apa-apa yang hilang.",
        "unexpected_error": "Ralat tidak dijangka berlaku:\n\n{error}",
    },
    "my": {
        "dialog_title": "Restart",
        "restart_checkbox": "Anki ကို ပြန်စတင်ရန် ဖြတ်လမ်းကို ဖွင့်ပါ",
        "close_checkbox": "Anki ကို ပိတ်ရန် ဖြတ်လမ်းကို ဖွင့်ပါ",
        "shortcut_label": "ဖြတ်လမ်း-",
        "restore_defaults": "မူလတန်ဖိုးများ ပြန်လည်ရယူပါ",
        "duplicate_shortcut": "ဖြတ်လမ်းနှစ်ခုသည် တူညီသောခလုတ်ပေါင်းစပ်မှု မဖြစ်နိုင်ပါ။",
        "error_title": "အမြန်ပြန်စတင်ခြင်း — အမှား",
        "executable_not_found": "Anki ပရိုဂရမ်ဖိုင်ကို ရှာမတွေ့သဖြင့် ပြန်စတင်၍မရပါ။ Anki ဖွင့်ထားဆဲဖြစ်ပြီး ဘာမှ ဆုံးရှုံးမှုမရှိပါ။",
        "unexpected_error": "မမျှော်လင့်သော အမှားတစ်ခု ဖြစ်ပွားခဲ့သည်-\n\n{error}",
    },
    "nb": {
        "dialog_title": "Restart",
        "restart_checkbox": "Aktiver snarvei for å starte Anki på nytt",
        "close_checkbox": "Aktiver snarvei for å lukke Anki",
        "shortcut_label": "Snarvei:",
        "restore_defaults": "Gjenopprett standardverdier",
        "duplicate_shortcut": "De to snarveiene kan ikke være samme tastekombinasjon.",
        "error_title": "Rask omstart — Feil",
        "executable_not_found": "Fant ikke programfilen til Anki, så den kan ikke startes på nytt. Anki forblir åpen og ingenting gikk tapt.",
        "unexpected_error": "Det oppsto en uventet feil:\n\n{error}",
    },
    "nl": {
        "dialog_title": "Restart",
        "restart_checkbox": "Sneltoets voor het herstarten van Anki inschakelen",
        "close_checkbox": "Sneltoets voor het sluiten van Anki inschakelen",
        "shortcut_label": "Sneltoets:",
        "restore_defaults": "Standaardwaarden herstellen",
        "duplicate_shortcut": "De twee sneltoetsen mogen niet dezelfde toetsencombinatie zijn.",
        "error_title": "Snel herstarten — Fout",
        "executable_not_found": "Het programmabestand van Anki is niet gevonden, dus herstarten is niet mogelijk. Anki blijft open en er is niets verloren gegaan.",
        "unexpected_error": "Er is een onverwachte fout opgetreden:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Steun de ontwikkeling op Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Beoordeel deze add-on",
        "report_button": "Bug melden",
        "welcome_close": "Sluiten",
        "welcome_body": "Quick Restart voegt een sneltoets toe om Anki direct opnieuw te starten of te sluiten, zonder de muis te gebruiken. Je kunt de sneltoetsen altijd wijzigen via Extra → Add-ons → Config.",
        "welcome_support_note": "Deze add-on is gratis en open source (AGPLv3). Als je hem nuttig vindt, overweeg dan de ontwikkeling te steunen.",
    },
    "oc": {
        "dialog_title": "Restart",
        "restart_checkbox": "Activar l'acorchi per reaviar Anki",
        "close_checkbox": "Activar l'acorchi per tampar Anki",
        "shortcut_label": "Acorchi :",
        "restore_defaults": "Restablir las valors per defaut",
        "duplicate_shortcut": "Los dos acorchis pòdon pas èsser la meteissa combinason de tòcas.",
        "error_title": "Reaviada rapida — Error",
        "executable_not_found": "Lo fichièr programa d'Anki es introbable, doncas se pòt pas reaviar. Anki demòra dobèrt e res s'es pas perdut.",
        "unexpected_error": "Una error inesperada s'es producha :\n\n{error}",
    },
    "pl": {
        "dialog_title": "Restart",
        "restart_checkbox": "Włącz skrót do ponownego uruchomienia Anki",
        "close_checkbox": "Włącz skrót do zamknięcia Anki",
        "shortcut_label": "Skrót:",
        "restore_defaults": "Przywróć wartości domyślne",
        "duplicate_shortcut": "Oba skróty nie mogą być tą samą kombinacją klawiszy.",
        "error_title": "Szybki restart — Błąd",
        "executable_not_found": "Nie znaleziono pliku programu Anki, więc nie można go uruchomić ponownie. Anki pozostaje otwarte i nic nie zostało utracone.",
        "unexpected_error": "Wystąpił nieoczekiwany błąd:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Wesprzyj rozwój na Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Oceń ten dodatek",
        "report_button": "Zgłoś błąd",
        "welcome_close": "Zamknij",
        "welcome_body": "Quick Restart dodaje skrót klawiszowy do natychmiastowego ponownego uruchamiania lub zamykania Anki, bez sięgania po mysz. Skróty możesz zmienić w dowolnym momencie w Narzędzia → Dodatki → Konfiguruj.",
        "welcome_support_note": "Ten dodatek jest darmowy i open source (AGPLv3). Jeśli uważasz go za przydatny, rozważ wsparcie jego rozwoju.",
    },
    "pt_BR": {
        "dialog_title": "Restart",
        "restart_checkbox": "Ativar atalho para reiniciar o Anki",
        "close_checkbox": "Ativar atalho para fechar o Anki",
        "shortcut_label": "Atalho:",
        "restore_defaults": "Restaurar os valores padrão",
        "duplicate_shortcut": "Os dois atalhos não podem ser a mesma combinação de teclas.",
        "error_title": "Reinício rápido — Erro",
        "executable_not_found": "O arquivo de programa do Anki não foi encontrado, então não é possível reiniciar. O Anki continua aberto e nada foi perdido.",
        "unexpected_error": "Ocorreu um erro inesperado:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Apoie o desenvolvimento no Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Avaliar este complemento",
        "report_button": "Reportar um erro",
        "welcome_close": "Fechar",
        "welcome_body": "Quick Restart adiciona um atalho para reiniciar ou fechar o Anki instantaneamente, sem precisar do mouse. Você pode alterar os atalhos quando quiser em Ferramentas → Complementos → Config.",
        "welcome_support_note": "Este complemento é gratuito e de código aberto (AGPLv3). Se for útil para você, considere apoiar o desenvolvimento.",
    },
    "pt_PT": {
        "dialog_title": "Restart",
        "restart_checkbox": "Ativar atalho para reiniciar o Anki",
        "close_checkbox": "Ativar atalho para fechar o Anki",
        "shortcut_label": "Atalho:",
        "restore_defaults": "Restaurar os valores predefinidos",
        "duplicate_shortcut": "Os dois atalhos não podem ser a mesma combinação de teclas.",
        "error_title": "Reinício rápido — Erro",
        "executable_not_found": "O ficheiro de programa do Anki não foi encontrado, pelo que não é possível reiniciar. O Anki mantém-se aberto e nada se perdeu.",
        "unexpected_error": "Ocorreu um erro inesperado:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Apoie o desenvolvimento no Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Avaliar esta extensão",
        "report_button": "Reportar um erro",
        "welcome_close": "Fechar",
        "welcome_body": "Quick Restart adiciona um atalho para reiniciar ou fechar o Anki instantaneamente, sem precisar do rato. Pode alterar os atalhos quando quiser em Ferramentas → Extensões → Configurar.",
        "welcome_support_note": "Esta extensão é gratuita e de código aberto (AGPLv3). Se lhe for útil, considere apoiar o seu desenvolvimento.",
    },
    "ro": {
        "dialog_title": "Restart",
        "restart_checkbox": "Activează scurtătura pentru repornirea Anki",
        "close_checkbox": "Activează scurtătura pentru închiderea Anki",
        "shortcut_label": "Scurtătură:",
        "restore_defaults": "Restabilește valorile implicite",
        "duplicate_shortcut": "Cele două scurtături nu pot fi aceeași combinație de taste.",
        "error_title": "Repornire rapidă — Eroare",
        "executable_not_found": "Fișierul programului Anki nu a fost găsit, deci nu poate reporni. Anki rămâne deschis și nu s-a pierdut nimic.",
        "unexpected_error": "A apărut o eroare neașteptată:\n\n{error}",
    },
    "ru": {
        "dialog_title": "Restart",
        "restart_checkbox": "Включить сочетание клавиш для перезапуска Anki",
        "close_checkbox": "Включить сочетание клавиш для закрытия Anki",
        "shortcut_label": "Сочетание клавиш:",
        "restore_defaults": "Восстановить значения по умолчанию",
        "duplicate_shortcut": "Оба сочетания клавиш не могут быть одинаковыми.",
        "error_title": "Быстрый перезапуск — Ошибка",
        "executable_not_found": "Программный файл Anki не найден, поэтому перезапуск невозможен. Anki остаётся открытым, ничего не потеряно.",
        "unexpected_error": "Произошла непредвиденная ошибка:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Поддержите разработку на Ko-fi",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Оценить дополнение",
        "report_button": "Сообщить об ошибке",
        "welcome_close": "Закрыть",
        "welcome_body": "Quick Restart добавляет сочетание клавиш для мгновенного перезапуска или закрытия Anki без использования мыши. Сочетания можно изменить в любой момент в меню Инструменты → Дополнения → Настройка.",
        "welcome_support_note": "Это дополнение бесплатное и с открытым исходным кодом (AGPLv3). Если оно вам полезно, рассмотрите возможность поддержать его разработку.",
    },
    "sk": {
        "dialog_title": "Restart",
        "restart_checkbox": "Zapnúť skratku na reštart Anki",
        "close_checkbox": "Zapnúť skratku na zatvorenie Anki",
        "shortcut_label": "Skratka:",
        "restore_defaults": "Obnoviť predvolené hodnoty",
        "duplicate_shortcut": "Obe skratky nemôžu byť rovnaká kombinácia klávesov.",
        "error_title": "Rýchly reštart — Chyba",
        "executable_not_found": "Programový súbor Anki sa nenašiel, takže ho nemožno reštartovať. Anki zostáva otvorené a nič sa nestratilo.",
        "unexpected_error": "Vyskytla sa neočakávaná chyba:\n\n{error}",
    },
    "sl": {
        "dialog_title": "Restart",
        "restart_checkbox": "Omogoči bližnjico za ponovni zagon Anki",
        "close_checkbox": "Omogoči bližnjico za zaprtje Anki",
        "shortcut_label": "Bližnjica:",
        "restore_defaults": "Obnovi privzete vrednosti",
        "duplicate_shortcut": "Bližnjici ne smeta biti ista kombinacija tipk.",
        "error_title": "Hiter ponovni zagon — Napaka",
        "executable_not_found": "Programske datoteke Anki ni bilo mogoče najti, zato ponovni zagon ni mogoč. Anki ostaja odprt in nič ni izgubljeno.",
        "unexpected_error": "Prišlo je do nepričakovane napake:\n\n{error}",
    },
    "sq": {
        "dialog_title": "Restart",
        "restart_checkbox": "Aktivizo shkurtoren për rinisjen e Anki-t",
        "close_checkbox": "Aktivizo shkurtoren për mbylljen e Anki-t",
        "shortcut_label": "Shkurtore:",
        "restore_defaults": "Rikthe vlerat e parazgjedhura",
        "duplicate_shortcut": "Dy shkurtoret nuk mund të jenë i njëjti kombinim tastesh.",
        "error_title": "Rinisje e shpejtë — Gabim",
        "executable_not_found": "Skedari i programit Anki nuk u gjet, prandaj nuk mund të rinisë. Anki mbetet i hapur dhe asgjë nuk humbi.",
        "unexpected_error": "Ndodhi një gabim i papritur:\n\n{error}",
    },
    "sr": {
        "dialog_title": "Restart",
        "restart_checkbox": "Омогући пречицу за поновно покретање Анкија",
        "close_checkbox": "Омогући пречицу за затварање Анкија",
        "shortcut_label": "Пречица:",
        "restore_defaults": "Врати подразумеване вредности",
        "duplicate_shortcut": "Две пречице не могу бити иста комбинација тастера.",
        "error_title": "Брзо поновно покретање — Грешка",
        "executable_not_found": "Програмска датотека Анкија није пронађена, па се не може поново покренути. Анки остаје отворен и ништа није изгубљено.",
        "unexpected_error": "Дошло је до неочекиване грешке:\n\n{error}",
    },
    "sv": {
        "dialog_title": "Restart",
        "restart_checkbox": "Aktivera kortkommando för att starta om Anki",
        "close_checkbox": "Aktivera kortkommando för att stänga Anki",
        "shortcut_label": "Kortkommando:",
        "restore_defaults": "Återställ standardvärden",
        "duplicate_shortcut": "De två kortkommandona kan inte vara samma tangentkombination.",
        "error_title": "Snabb omstart — Fel",
        "executable_not_found": "Ankis programfil kunde inte hittas, så den kan inte startas om. Anki förblir öppet och inget gick förlorat.",
        "unexpected_error": "Ett oväntat fel inträffade:\n\n{error}",
    },
    "th": {
        "dialog_title": "Restart",
        "restart_checkbox": "เปิดใช้ทางลัดสำหรับรีสตาร์ท Anki",
        "close_checkbox": "เปิดใช้ทางลัดสำหรับปิด Anki",
        "shortcut_label": "ทางลัด:",
        "restore_defaults": "คืนค่าเริ่มต้น",
        "duplicate_shortcut": "ทางลัดทั้งสองต้องไม่ใช่ปุ่มผสมเดียวกัน",
        "error_title": "รีสตาร์ทด่วน — ข้อผิดพลาด",
        "executable_not_found": "ไม่พบไฟล์โปรแกรมของ Anki จึงไม่สามารถรีสตาร์ทได้ Anki ยังเปิดอยู่และไม่มีข้อมูลใดสูญหาย",
        "unexpected_error": "เกิดข้อผิดพลาดที่ไม่คาดคิด:\n\n{error}",
    },
    "tl": {
        "dialog_title": "Restart",
        "restart_checkbox": "Paganahin ang shortcut para i-restart ang Anki",
        "close_checkbox": "Paganahin ang shortcut para isara ang Anki",
        "shortcut_label": "Shortcut:",
        "restore_defaults": "Ibalik ang mga default na halaga",
        "duplicate_shortcut": "Hindi maaaring magkapareho ang dalawang shortcut.",
        "error_title": "Mabilis na Restart — Error",
        "executable_not_found": "Hindi mahanap ang program file ng Anki, kaya hindi ito maaaring i-restart. Nananatiling bukas ang Anki at walang nawala.",
        "unexpected_error": "May naganap na hindi inaasahang error:\n\n{error}",
    },
    "tr": {
        "dialog_title": "Restart",
        "restart_checkbox": "Anki'yi yeniden başlatma kısayolunu etkinleştir",
        "close_checkbox": "Anki'yi kapatma kısayolunu etkinleştir",
        "shortcut_label": "Kısayol:",
        "restore_defaults": "Varsayılan değerleri geri yükle",
        "duplicate_shortcut": "İki kısayol aynı tuş bileşimi olamaz.",
        "error_title": "Hızlı yeniden başlatma — Hata",
        "executable_not_found": "Anki'nin program dosyası bulunamadı, bu yüzden yeniden başlatılamıyor. Anki açık kalır ve hiçbir şey kaybolmaz.",
        "unexpected_error": "Beklenmeyen bir hata oluştu:\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "Ko-fi'de geliştirmeyi destekleyin",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 Bu eklentiyi değerlendirin",
        "report_button": "Hata bildir",
        "welcome_close": "Kapat",
        "welcome_body": "Quick Restart, fareye dokunmadan Anki'yi anında yeniden başlatmak veya kapatmak için bir kısayol ekler. Kısayolları istediğiniz zaman Araçlar → Eklentiler → Yapılandır bölümünden değiştirebilirsiniz.",
        "welcome_support_note": "Bu eklenti ücretsiz ve açık kaynaklıdır (AGPLv3). Faydalı bulduysanız geliştirilmesine destek olmayı düşünebilirsiniz.",
    },
    "ug": {
        "dialog_title": "Restart",
        "restart_checkbox": "Anki نى قايتا قوزغىتىش تېزلەتمىسىنى قوزغىتىش",
        "close_checkbox": "Anki نى تاقاش تېزلەتمىسىنى قوزغىتىش",
        "shortcut_label": "تېزلەتمە:",
        "restore_defaults": "كۆڭۈلدىكى قىممەتلەرنى ئەسلىگە كەلتۈرۈش",
        "duplicate_shortcut": "ئىككى تېزلەتمە ئوخشاش كۇنۇپكا بىرىكمىسى بولسا بولمايدۇ.",
        "error_title": "تېز قايتا قوزغىتىش — خاتالىق",
        "executable_not_found": "Anki پروگرامما ھۆججىتى تېپىلمىدى، شۇڭا قايتا قوزغىتالمايدۇ. Anki ئوچۇق تۇرىدۇ ۋە ھېچنېمە يوقالمىدى.",
        "unexpected_error": "ئويلىمىغان خاتالىق كۆرۈلدى:\n\n{error}",
    },
    "uk": {
        "dialog_title": "Restart",
        "restart_checkbox": "Увімкнути комбінацію для перезапуску Anki",
        "close_checkbox": "Увімкнути комбінацію для закриття Anki",
        "shortcut_label": "Комбінація клавіш:",
        "restore_defaults": "Відновити типові значення",
        "duplicate_shortcut": "Дві комбінації клавіш не можуть бути однаковими.",
        "error_title": "Швидкий перезапуск — Помилка",
        "executable_not_found": "Програмний файл Anki не знайдено, тому перезапуск неможливий. Anki залишається відкритим, нічого не втрачено.",
        "unexpected_error": "Сталася неочікувана помилка:\n\n{error}",
    },
    "uz": {
        "dialog_title": "Restart",
        "restart_checkbox": "Anki'ni qayta ishga tushirish tugmasini yoqish",
        "close_checkbox": "Anki'ni yopish tugmasini yoqish",
        "shortcut_label": "Tezkor tugma:",
        "restore_defaults": "Standart qiymatlarni tiklash",
        "duplicate_shortcut": "Ikkala tezkor tugma bir xil bo'lishi mumkin emas.",
        "error_title": "Tez qayta ishga tushirish — Xato",
        "executable_not_found": "Anki dastur fayli topilmadi, shuning uchun uni qayta ishga tushirib bo'lmaydi. Anki ochiq qoladi va hech narsa yo'qolmadi.",
        "unexpected_error": "Kutilmagan xato yuz berdi:\n\n{error}",
    },
    "vi": {
        "dialog_title": "Restart",
        "restart_checkbox": "Bật phím tắt để khởi động lại Anki",
        "close_checkbox": "Bật phím tắt để đóng Anki",
        "shortcut_label": "Phím tắt:",
        "restore_defaults": "Khôi phục giá trị mặc định",
        "duplicate_shortcut": "Hai phím tắt không thể là cùng một tổ hợp phím.",
        "error_title": "Khởi động lại nhanh — Lỗi",
        "executable_not_found": "Không tìm thấy tệp chương trình của Anki nên không thể khởi động lại. Anki vẫn mở và không mất dữ liệu nào.",
        "unexpected_error": "Đã xảy ra lỗi không mong muốn:\n\n{error}",
    },
    "zh_CN": {
        "dialog_title": "Restart",
        "restart_checkbox": "启用重启 Anki 的快捷键",
        "close_checkbox": "启用关闭 Anki 的快捷键",
        "shortcut_label": "快捷键：",
        "restore_defaults": "恢复默认值",
        "duplicate_shortcut": "两个快捷键不能使用相同的组合键。",
        "error_title": "快速重启 — 错误",
        "executable_not_found": "找不到 Anki 的程序文件，因此无法重启。Anki 仍然打开，没有任何数据丢失。",
        "unexpected_error": "发生了意外错误：\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "在 Ko-fi 上支持开发",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 评价此附加组件",
        "report_button": "报告问题",
        "welcome_close": "关闭",
        "welcome_body": "Quick Restart 添加了一个快捷键，让你无需使用鼠标即可立即重启或关闭 Anki。你可以随时在 工具 → 附加组件 → 配置 中更改快捷键。",
        "welcome_support_note": "此附加组件免费且开源（AGPLv3）。如果你觉得有用，欢迎支持它的开发。",
    },
    "zh_TW": {
        "dialog_title": "Restart",
        "restart_checkbox": "啟用重新啟動 Anki 的快捷鍵",
        "close_checkbox": "啟用關閉 Anki 的快捷鍵",
        "shortcut_label": "快捷鍵：",
        "restore_defaults": "還原預設值",
        "duplicate_shortcut": "兩個快捷鍵不能是相同的組合鍵。",
        "error_title": "快速重新啟動 — 錯誤",
        "executable_not_found": "找不到 Anki 的程式檔案，因此無法重新啟動。Anki 仍然開啟，沒有任何資料遺失。",
        "unexpected_error": "發生未預期的錯誤：\n\n{error}",
        "version_line": "{name} v{version}",
        "welcome_title": "{name} v{version}",
        "kofi_button": "☕ Ko-fi",
        "kofi_tooltip": "在 Ko-fi 上支持開發",
        "patreon_button": "♥ Patreon",
        "rate_button": "👍 評價此外掛程式",
        "report_button": "回報問題",
        "welcome_close": "關閉",
        "welcome_body": "Quick Restart 新增了一個快捷鍵，讓你不需使用滑鼠即可立即重新啟動或關閉 Anki。你可以隨時在 工具 → 外掛程式 → 設定 中變更快捷鍵。",
        "welcome_support_note": "此外掛程式免費且開源（AGPLv3）。如果你覺得有用，歡迎支持它的開發。",
    },
}


def _active_lang() -> str:
    code = getattr(anki_lang, "current_lang", FALLBACK_LANG) or FALLBACK_LANG
    if code in _STRINGS:
        return code
    base = code.replace("-", "_").split("_", 1)[0]
    if base in _STRINGS:
        return base
    return FALLBACK_LANG


def tr(key: str, **values: str) -> str:
    table = _STRINGS.get(_active_lang(), _STRINGS[FALLBACK_LANG])
    text = table.get(key) or _STRINGS[FALLBACK_LANG].get(key, key)
    if values:
        try:
            return text.format(**values)
        except (KeyError, IndexError):
            return text
    return text